### ISSUE TITLE
No coloring

### ISSUE THREAD

**Issue by tek0011** [theforeman/foreman_datacenter#10]
What is the option of colors for?  I do not see any change in colors, no matter what I choose.   Is this for future features?

**Comment by Zenya** [comment]
@tek0011 This is created to visually identify the device and its role on the rack. For simpler physical management of devices

**Comment by tek0011** [comment]
But should I see colors on the rack page?

![image](https://user-images.githubusercontent.com/1085020/36101977-78eb0cd4-0fd0-11e8-9081-2989c7b4281f.png)

**Comment by zdenekjanda** [comment]
This is for tuture feature. @Zenya, propably we should set display color at device type ?

**Comment by tek0011** [comment]
Thanks!  I'll close this, was just curious.

**Comment by zdenekjanda** [comment]
So each device role has a color setting, like basic roles are server, switch, uplink, etc. We could optionally add also custom color for device type (like different types of servers), that override device role, but i dont think thats really much usable. @Zenya, please try to turn on the colors in rack view for next release.

**Comment by Zenya** [comment]
@tek0011 I tried to do it manually and it looks not informative and gets out of the general style of the plugin
![205db04d3c](https://user-images.githubusercontent.com/857289/36353930-c5c94304-14d5-11e8-9ffc-8c90c600fc60.jpg)
Also if you consider that it is possible the location of 2 devices on the same position (with different roles) - this looks worse

So I suggest to make it like this
![8583b495b3](https://user-images.githubusercontent.com/857289/36354803-64f33f28-14e2-11e8-9b48-c8fcca7e0143.jpg)
and yes, there is new table - unpositioned devices
