### ISSUE TITLE
New device does not allow to select device type and rack

### ISSUE THREAD

**Issue by dgoetz** [theforeman/foreman_datacenter#12]
I installed the plugin on a fresh installation of Foreman 1.17 (a demo for colleagues with forklift centos7-foreman-1.17). Afterwards I created one site "RZ1", one rack "Rack1" in "RZ1", one device role, one manufacturer "HP", one device type "Switch" from manufacture "HP" and then wanted to add a device "Switch1". I can select the created device role, manufacturer and site, but device type and rack are not offered by the dropdown box of the form. As these value are mandatory I am unable to save the device.

**Comment by Zenya** [comment]
@dgoetz Please execute assets precompilation and restart foreman. Possible reason of this problem - js error
We are working on this problem

**Comment by dgoetz** [comment]
@Zenya You are right, had to install gem uglifier and rpm nodejs, run the asset precompilation and restart foreman, now it works.

Is something of this needed as information for package build?

**Comment by zdenekjanda** [comment]
@Zenya, please specify all these requirements for package build and deployment - it seems uglifier gem, nodejs binary and assets precompilation are missed for package postinstall steps, so it never installs correctly without manual steps at this moment.

**Comment by zdenekjanda** [comment]
Closing this as documentation has been updated how to install and precompile assets, also this has been noted in known bugs.
