### ISSUE TITLE
Issues with Installation

### ISSUE THREAD

**Issue by smbambling** [theforeman/foreman_datacenter#3]
Issues with install/setup.  I believe I have correctly followed the docs for installing the plugin and restarted the Foreman service via Apache passenger.  I can't see any change that was added in the web console. It seems there is a missing step for possibly running some rake migrate task to add additional data into the DB.

Here are my steps for installation

```
1. Install build requirements
  - yum install rh-ruby22-ruby-devel zlib-devel
2. Switch to the tfm SCL shell
  - scl enable tfm bash
3. Install the RubyGem
  - gem install --ignore-dependencies foreman_datacenter
4. Restart Foreman Service (HTTP Passenger)
  - service httpd restart
```

Here is the version I have currently installed
```
# gem list | grep datacenter
foreman_datacenter (0.1.40)
```

**Comment by smbambling** [comment]
I also don't see the plugin listed as installed when I click about/publins in the web console.

**Comment by zdenekjanda** [comment]
Have you followed official docs on installing plugins ? https://theforeman.org/plugins/#2.Installation . You have to add foreman_datacenter gem to Foreman's bundler.d directory and make bundle install, and then also precompile assets and migrate db, like bundle exec rake assets:precompile and bundle exec rake db:migrate. After this and apache restart, new datacenter tab should appear in UI and plugin will be functional. We are working on adding the plugin to foreman packaging, so this should get much easier in future.

**Comment by ohadlevy** [comment]
maybe its related to a db migration error, when trying it out i got the following error:
```
ActiveRecord::DuplicateMigrationNameError: 

Multiple migrations have the name AddParentIdToComments.
```

**Comment by zdenekjanda** [comment]
Thanks for feedback on this, we are looking into it. Tests with fresh foreman install will be done - we didn't encounter this migration issue yet.

**Comment by Zenya** [comment]
Correct - it's problem with migration. Wrong migration was created accidentally. Please use last version 0.1.43
Or you can freely delete the migration file `20170929072115_add_parent_id_to_comments.rb`
And please let us feedback
Thanks for your issue
