### ISSUE TITLE
Deleting a device does not work

### ISSUE THREAD

**Issue by tullis** [theforeman/foreman_datacenter#31]
When I select a device and try to delete it I get a message which says:

`ERF42-4995 [Foreman::Exception]: Invalid authenticity token`

I also note a 500 error in the logs: `POST /datacenter/devices/6 HTTP/1.1" 500`

When deleting I unselected the checkbox marked: **Delete associated host ONLY and keep current device as UNASSIGNED!** because I only want to delete the object from the datacentre plugin, not from the general list of hosts in Foreman.

Many thanks.

**Comment by Zenya** [comment]
Hi
please update gem for latest version
bug fixed

By unselecting checkbox you are deleting all associated objects like interfaces, connections, ports and all other stuff which belongs to current device

**Comment by tullis** [comment]
Hi @Zenya and thanks for the swift response.
I'm currently using Debian packages and I have the latest version that is available there.

```
deb http://deb.theforeman.org/ stretch 1.21
deb http://deb.theforeman.org/ plugins 1.21
```
Do I need to update to 1.22 to get this bug fix? I note that I also get a 404 if I try to move an object instead of delete it. Has this also been fixed? Would you like that to be filed separately?

```
# apt-cache policy ruby-foreman-datacenter 
ruby-foreman-datacenter:
  Installed: 1.20.0
  Candidate: 1.20.0
  Version table:
 *** 1.20.0 500
        500 http://deb.theforeman.org plugins/1.21 amd64 Packages
        100 /var/lib/dpkg/status
     0.1.44 500
        500 http://deb.theforeman.org plugins/1.21 amd64 Packages
```

**Comment by Zenya** [comment]
I mean latest version of foreman_datacenter gem
I suppose it's 1.20.4(you can find it here
https://rubygems.org/gems/foreman_datacenter)
I guess here is some problem with .deb package
I will fix it

**Comment by tullis** [comment]
Thanks @Zenya, I look forward to trying it out.
I'm wary of installing the gem because of the advice given here:

https://theforeman.org/plugins/#2.3AdvancedInstallationfromGems
> Not recommended, as it’s possible for the ‘gem’ command to install other, newer dependencies, which can cause problems with the Foreman installation. 

This is a Foreman instance that is in production, so I'd rather stick with the packages if possible. I'll await an update.

**Comment by Zenya** [comment]
I created pull request to add datacenter version 1.20.4 into theforeman deb repo

**Comment by tullis** [comment]
I see it. Many thanks. https://github.com/theforeman/foreman-packaging/pull/3861

**Comment by tullis** [comment]
Hi @Zenya, did you spot that your PR was closed, asking it to be raised against `deb/develop` instead of `deb/1.20`?

**Comment by tullis** [comment]
This is fixed in the latest version, as correctly stated by @Zenya .
