### ISSUE TITLE
Integration with RackTables

### ISSUE THREAD

**Issue by Raboo** [theforeman/foreman_datacenter#5]
Interesting plugin, it would be nice if it were integrated with [RackTables](https://github.com/RackTables/racktables) somehow.

Is this something you have thought about or perhaps you didn't even know about RackTables?
Anyways just a feature idea here..

**Comment by zdenekjanda** [comment]
Thanks for feedback. I did a quick overview of RackTables, and i do see both Foreman and our plugin already covers most of what RackTables do, so integrating it would be a duplicate. However, If you find some interesting feature which is in RackTables and missing here, feel free to suggest - if we find it interesting and usable in real life, we will add it. Closing this issue for now.

**Comment by Raboo** [comment]
Makes perfect sense. It was mostly the visuals/browser i like about RackTables. Perhaps I should make a feature request for that..
<img width="215" alt="screen shot 2017-11-25 at 17 37 34" src="https://user-images.githubusercontent.com/1148206/33232499-c1eabdf0-d207-11e7-8705-9d4d93807eb7.png">
<img width="346" alt="screen shot 2017-11-25 at 17 37 55" src="https://user-images.githubusercontent.com/1148206/33232500-c67ce636-d207-11e7-9fc8-44908e360003.png">

**Comment by zdenekjanda** [comment]
This already exists, if you go into rack you see visual representation of devices in rack. I agree its not that visually aestetic as your screenshot above, but it does the job:

![image](https://user-images.githubusercontent.com/3619974/33234455-7434cb26-d227-11e7-8dce-dba638b30ffa.png)

**Comment by Raboo** [comment]
ohh, didn't realize, then i'm sold, installing the plugin next week :-)
