### ISSUE TITLE
Index names too long for sqlite

### ISSUE THREAD

**Issue by jovandeginste** [theforeman/foreman_datacenter#6]
I run a test setup of foreman using a sqlite database, and `db:migrate` with the datacenter plugin installed complains:

```
StandardError: An error has occurred, this and all later migrations canceled:

Index name 'index_datacenter_comments_on_commentable_id_and_commentable_type' on table 'datacenter_comments' is too long; the limit is 62 characters
/foreman/vendor/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/schema_statements.rb:1049:in `validate_index_length!'
```

**Comment by Zenya** [comment]
Thanks for info
We are now working on the test part of the plugin
Problem will be fixed soon

**Comment by zdenekjanda** [comment]
@jovandeginste please check latest version, problem should be fixed. Let us know, if it works for you.

**Comment by zdenekjanda** [comment]
@Zenya can you check and confirm this has been fixed ? I would like to close this issue asap.
