### ISSUE TITLE
any screenshots of what this looks like?

### ISSUE THREAD

**Issue by tek0011** [theforeman/foreman_datacenter#8]
This sounds amazing.  Any screenshots of what this looks like?

**Comment by miksercz** [comment]
Hello,
good idea, we will add them soon :)

**Comment by ThoTischner** [comment]
There is a pretty nice youtube video https://www.youtube.com/watch?v=HVmJ6UYPaz0

**Comment by zdenekjanda** [comment]
Closing this, video has been linked in readme so we have definitive answer for this
